### ISSUE TITLE
commands.html issue

### ISSUE THREAD

**Issue by vyasamit** [Spaceface16518/Ruffle#12]
js needs to be referenced using script tag not link tag as your js is local not on the CDN

   <script LANGUAGE="JavaScript" src="linked/functions.js"></scrip

**Comment by Spaceface16518** [comment]
Oh okay. I should have thought of that! Thank!

**Comment by Spaceface16518** [comment]
Should I assign the `src` attribute  to  `./linked/functions.js` or just `linked/functions.js`?
