### ISSUE TITLE
Entire page is missing

### ISSUE THREAD

**Issue by Spaceface16518** [Spaceface16518/Ruffle#13]
@vyasamit something went wrong when I was trying to fix the script error. Can you take a look at it?  
It could be that the script  looks like this:
~~~~
<script lang="javascript" src="./linked/functions.js" />
~~~~
instead of this:
~~~~
<script lang="javascript" src="./linked/functions.js"></script>
~~~~
Could that be the issue? Please let me know. Thanks!

**Comment by vyasamit** [comment]
@Spaceface16518 html5 doesn't support the self-closing tag for the script.

https://stackoverflow.com/questions/69913/why-dont-self-closing-script-tags-work

**Comment by Spaceface16518** [comment]
Okay thanks I think it works now!
